name: Hello, World

on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: echo hello, world
        run: echo "Hello, world"

      # - name: print title
      #   run: echo "${{ github.event.issue.title }}"
